### ISSUE TITLE
Where can I find the API documentation?

### ISSUE THREAD

**Issue by owendelong** [lexus2k/lcdgfx#10]
I'm sure this is poor search-engine foo on my part (or some other dumb error), but I'm having a devil of a time finding a basic reference for the API or tutorial to let me just make basic use of the library.

I found the FAQs, I found how to add fonts, I found how to set up the hardware (though I had the hardware running the demo before I went looking), I found how to instantiate the class, and I understand from reviewing the source to the demo how to do some basic operations in the code. I even found the list of available fonts.

What I haven't found is any sort of API documentation or reference.

Pointer appreciated.

Update of FAQ and other READMEs to include this pointer very much appreciated.

**Comment by lexus2k** [comment]
Hi,

The best way to understand, how to use the library, are examples. However, there is some documentation, generated by doxygen tool. You can find it in `docs` folders of the library sources, and open it with any favorite browser, also, the documentation is available on the link, provided on the home page: 

> For more information about this library, please, visit https://github.com/lexus2k/lcdgfx. Doxygen documentation can be found at [github.io site](http://lexus2k.github.io/lcdgfx).
