### ISSUE TITLE
Add ARC to Circle

### ISSUE THREAD

**Issue by schwos** [lexus2k/lcdgfx#107]
This isn't related to any known problem with the 
Circle function just like to port some code from u2g2 to this library. Within u2g2 there is the ability to create an arc using the circle function. 

Basically, it could be added to the Circle function as an ending variable that would be optional. 

This would permit one to create a half circle from the bottom of the screen arching could be used for various tools like simulated analog volt meter or vu meter.

Let me know if there is more information requested.

**Comment by lexus2k** [comment]
Please check the mainline, if this is what you were writing about.

**Comment by schwos** [comment]
I see we can draw a circle via a drawCircle(lcdint_t xc, lcdint_t yc, lcdint_t r, uint8_t options) but would be beneficial if we could as to only draw saw a 1/4 of it. like top right, top left now you have a half circle from bottom right of screen arc'd to left of screen.
