### ISSUE TITLE
printFixed y is limited to 8-pixel steps

### ISSUE THREAD

**Issue by octave** [lexus2k/lcdgfx#11]
Hi!

When using `printFixed` I'm limited to 8-pixel step for the y axis. Is there any way to display a font at a custom y location? I'm using the library with a `SD1306_128x64_I2C`.

Thank you!

**Comment by lexus2k** [comment]
Hi,

Yeap, this is how printFixed works for monochrome displays (it supports more styles than for color displays). However, you can use:
```.cpp
    display.setTextCursor(x,y);
    display.write("Hello");
```

**Comment by octave** [comment]
Got it! Thank you I will using this!
