### ISSUE TITLE
ESP8266 demo compilation error: fatal error: driver/spi_master.h: No such file or directory

### ISSUE THREAD

**Issue by remzibi** [lexus2k/lcdgfx#111]
**Describe the bug**
Arduino IDE 2.2.1 fresh installed, fresh installed lcdgfx library, st7735 and ili9341 demos not compile for esp8266 board with this error:
libraries\lcdgfx\src/lcd_hal/esp/esp32_spi.h:34:10: fatal error: driver/spi_master.h: No such file or directory
   34 | #include "driver/spi_master.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated. 

**To Reproduce**
1. install Arduino IDE 2.2.1, install lcdgfx library 1.1.5 from library manager
2. Click on 'compile'
3. Scroll down to read error
4. See error :
 libraries\lcdgfx\src/lcd_hal/esp/esp32_spi.h:34:10: fatal error: driver/spi_master.h: No such file or directory
   34 | #include "driver/spi_master.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated. 

**Expected behavior**
sd1306 library demos compiling and works well with this particular MCU board and this particular ili9341 display, so hardware is OK.

**Screenshots**

**Please complete the following information:**
 - library version : Using library lcdgfx at version 1.1.5
 - LCD display type : ili9341
 - OS  windows10
 - Platform esp8266 generic
 - IDE Arduino 2.2.1

**Additional context**
no additional context

**Comment by oiv** [comment]
It looks like #define CONFIG_ESP32_SPI_AVAILABLE is misplaced in lcdgfx/src/lcd_hal/arduino/io.h 
Commenting it out helped for me as a temporary solution
