### ISSUE TITLE
Added macOS support in emulation mode

### ISSUE THREAD

**Issue by enekochan** [lexus2k/lcdgfx#18]
I've added support for emulation in macOS. The code if you want to check it out: https://github.com/enekochan/lcdgfx

I'll do a PR if you consider this appropriate.

Basically I've installed SDL 2.0 with MacPorts (but you could use Brew or the original SDL 2 code as long as you use CFLAGS to include the headers folder location), added/changed some Makefiles and put some `defined(__APPLE__)` in the LCD HAL code.

I added the new `defined(__APPLE__)` statements in the original `src/lcd_hal/linux` code because everything is the same but for Linux Kernel I2C and SPI devel header references (that are not included in macOS). If a new folder with `src/lcd_hal/mac` should be created just tell me.

Some new docs should be added too in the [Wiki](https://github.com/lexus2k/lcdgfx/wiki/How-to-run-emulator-mode). The process should be something like this:

```
sudo port install libsdl2
cd tools/sdl
make -f Makefile.mac CFLAGS=-I/opt/local/include/
cd ../../src
make -f Makefile.mac SDL_EMULATION=y
cd ../tools
./build_and_run.sh -p mac -e -f demos/ssd1306_demo
./build_and_run.sh -p mac -e -f games/arkanoid8
```

If you install SDL from source `CFLAGS=-I/opt/local/include/` wont needed because it will most probably be located in `/usr/local/include/` and directly included.

I've also fixed some Makefile and Markdown errors (the build folder was not always created and links in the TOC section wouldn't work).

**Comment by lexus2k** [comment]
Hello,

Thank you for the interest to the library. Of course, pull request is welcome, if it doesn't break the library. I will add information on wiki as soon, as pull request is merged. 

I prefer to merge new code to development branch v1.0.0_dev, but it is ok to create request for master. If you have any ideas how to check mac os compilation automatically using travis ci, it would be also helpful.

Thank you, best regards
