### ISSUE TITLE
SH1106 not working..

### ISSUE THREAD

**Issue by VICLER** [lexus2k/lcdgfx#21]
I tried to flash an example for SH1106 and the display just stay black all the time after flashing. If I flash the same example for SSD1306 it works, but corrupted because I have SH1106. Im using Arduino Micro with Atmega32u4.

**Comment by lexus2k** [comment]
Hi, thank you for reporting the issue.
I will check the problem and come back to you with comments.

Also, could you please try old library version from https://github.com/lexus2k/ssd1306 and let me know if sh1106 demo works for you there?

**Comment by VICLER** [comment]
thank you for fast response!
sh1106 demo from the old library works as expected!
I would like to add some cyrillic fonts, how can I do that?

**Comment by lexus2k** [comment]
You can try to generate font using `./fontgenerator.py --ttf consola.ttf -s 6 -f new -g А я` line.
Still looking into issue with displays

**Comment by lexus2k** [comment]
Hello,

I found a bug in the library, and hope that my latest commit fixes it.
Could you please check lcdgfx library once again?

Thank you

**Comment by VICLER** [comment]
It works now! Thank you!
