### ISSUE TITLE
I made a font converter that converts bdf to free lcdgfx format.

### ISSUE THREAD

**Issue by mayopan** [lexus2k/lcdgfx#26]
Hi, lexus2k!
Thank you for the nice lcd driver. I like it rather than complex and huge [Adafruit-GFX-Library](https://github.com/adafruit/Adafruit-GFX-Library).
I also like [U8G2 driver](https://github.com/olikraus/u8g2) that is a similar driver especially for monochrome displays.
It has a lot of fonts, but lcdgfx has a few.

So I made a [font converter](https://github.com/mayopan/bdf2lcdgfx) for your driver.

It converts bdf font to lcdgfx c style free (= proportional) font.
Now, I can use many bdf fonts!
Check it and if you like it, please add it in tool family for others.
Thanks.

**Comment by lexus2k** [comment]
Hi there,

I'm really appreciate your effort, and of course I will add link to your converter to wiki pages.

Thank you

**Comment by lexus2k** [comment]
I've updated wiki page: https://github.com/lexus2k/lcdgfx/wiki/How-to-create-new-font-for-the-library

**Comment by mayopan** [comment]
Thank you for your quick response!
