### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by myval** [lexus2k/lcdgfx#29]
Not bug as such in the library but the link to the documentation is not working.

**Comment by lexus2k** [comment]
Could you please describe, which link doesn't work. 
https://codedocs.xyz/lexus2k/lcdgfx

**Comment by myval** [comment]
yeah sorry should have specify better. The link in the documentation section here:

Documentation generated by doxygen tool can be found at lcdgfx github.io site. 
this link:
`http://lexus2k.github.io/lcdgfx`

**Comment by myval** [comment]
Yeah the one you sent is fine, thanks. The link in document section might need to be updated.

**Comment by lexus2k** [comment]
Thank you, now fixed.
Could you check please ?

**Comment by myval** [comment]
Works first class now, thanks.
while I got you on line can you provide an example for printFixedPgm()? I have been struggling with it a bit.
And second question what is the function to set cursor for lets say print()?

thanks

**Comment by lexus2k** [comment]
> while I got you on line can you provide an example for printFixedPgm()?
Which platform? AVR?

```.cpp
const char * PROGMEM text = "Text from flash memory"
...
display.printFixedPgm(0,0, text);
```

> And second question what is the function to set cursor for lets say print()?

`display.setCursor()`. Does it work for you?
