### ISSUE TITLE
How to use DisplaySSD1306_128x32_CustomI2C

### ISSUE THREAD

**Issue by dansleboby** [lexus2k/lcdgfx#45]
Hi I don't have access to standard I2C pin how I can use a custom one?

Thanks

**Comment by lexus2k** [comment]
Hi,
There is no ready to use example for custom I2c, but there is an example [CustomSPI](https://github.com/lexus2k/lcdgfx/blob/master/examples/interfaces/custom_spi/custom_spi.ino).
You can use it as base for i2c development

Best regards

**Comment by lexus2k** [comment]
Hi, did you figure out how to use CustomI2C?

> I don't have access to standard I2C pin how I can use a custom one?

if you still have the problem, you need to provide more information on hardware platform, schematics of your setup, the code example. Not all pins can be used for i2c communication.

Best regards
