### ISSUE TITLE
Set different sizes on one Font

### ISSUE THREAD

**Issue by Danixu** [lexus2k/lcdgfx#47]
Hello,

I'm migrating from Adafruit library to this library to control an ST7735 display, because uses less RAM and Program space and my program need it.

My question is if is possible to use one font and change their size, because If not I will have to use two different fonts and uses more program memory. I've found that exists a function called printFixedN, but or I don't know how to use it, or is not available to my display.

Thanks!

**Comment by Danixu** [comment]
Looking into another issue I have seen this:

> > Can the font size be changed in this function?
> 
> No, the only supported feature is for monochrome displays. `printFixedN`

So I think that maybe my question is answered...

**Comment by lexus2k** [comment]
HI @Danixu,

Unfortunately printFixedN works only for monochrome displays. I can try to do quick porting of this function for color displays, but the speed of printFixedN will not be as fast, as it could.

**Comment by Danixu** [comment]
Thanks!!, I will try to figure out which letters are being used on my project to remove the others and try to free some space. Without do it I have already saved about 14% of Program Memory just changing the library, so maybe is enough for my program.

**Comment by lexus2k** [comment]
Please, check latest commit with printFixedN support for 16-bit displays

**Comment by Danixu** [comment]
Oh, thanks!!. I'll take a look

Best regards.
