### ISSUE TITLE
Support for ST7735 80x160 0,96''

### ISSUE THREAD

**Issue by T94T** [lexus2k/lcdgfx#51]
Is there a way to support the smaller ST7735 TFT display?
![grafik](https://user-images.githubusercontent.com/17198363/111028989-8caad280-83fa-11eb-92a6-92578a78e9c4.png)

**Comment by lexus2k** [comment]
Hello again,

So, could you please send me a link to datasheet, and let me know what happens, when using DisplayST7735_128x160x16_CustomSPI constructor. Thank you

Best regards

**Comment by T94T** [comment]
It's working quite well at this point. I think, it is only a question of resolution. 
[0.96 inch 80x160 IPS LCD.pdf](https://github.com/lexus2k/lcdgfx/files/6134934/0.96.inch.80x160.IPS.LCD.pdf)

<img width="200" alt="grafik" src="https://user-images.githubusercontent.com/17198363/111032921-f3d28200-840e-11eb-97ff-56f832752677.png">

**Comment by lexus2k** [comment]
Please, find initial support for the display on master branch.
For testing, don't forget to change 128x160 in the demo code to 80x160 (there are 2 such places).
And could you please capture screenshots for me for all rotation options (0,1,2,3)?

PS. Don't worry about `drawBitmap()` issues with owl. That's because the picture is of 128x64 size, while drawBitmap() doesn't support clipping.

**Comment by T94T** [comment]
These are the results:
**Rotation 0**
<img width="160" alt="Rotation0" src="https://user-images.githubusercontent.com/17198363/111111323-68680680-855e-11eb-9602-7f46f39aa6d7.png">
**Rotation 1**
<img width="160" alt="Rotation1" src="https://user-images.githubusercontent.com/17198363/111111334-6b62f700-855e-11eb-9e75-81e338072e57.png">
**Rotation 2**
<img width="181" alt="Rotation2" src="https://user-images.githubusercontent.com/17198363/111111337-6bfb8d80-855e-11eb-8169-d23fcbffc09c.png">
**Rotation 3**
<img width="160" alt="Rotation3" src="https://user-images.githubusercontent.com/17198363/111111339-6c942400-855e-11eb-8504-194c40d784c6.png">

**Comment by lexus2k** [comment]
Thank you. It looks like real lcd works, the problem only remains in the emulator.
