### ISSUE TITLE
I2C pins

### ISSUE THREAD

**Issue by Alvatros96** [lexus2k/lcdgfx#54]
Hello, and thank you foe this library.
I tried to look for a method but i can´t find anything. 
How is the method to change i2c pins to work whit arduino Mega and ssd1327 128x128?

**Comment by lexus2k** [comment]
HI

If the standard Arduino Wire library supports pins reassignment for i2c on Atmega2560, let me know.
I didn't find any information that Atmega2560 can use other than 21/20 pins.

Best regards

**Comment by Alvatros96** [comment]
Thank you very much for your quick response.
I'm trying the example ssd1327 that comes with the library but i'm unable to show anything in the screen with those pins connected. I also tried with other libaries in which I put pins 20 and 21 in the code and works fine, so i don't know what is happening.
Thank you very much anyway, i'll keep trying and let you know.

**Comment by Alvatros96** [comment]
Hi,
I've finally gotten it to work. With the I2C scanner doesn´t show anything but when I´ve connected an other device (RTC3231) , the scan shows the address correctly, so I've plug the screen and the RTC, and address of the screen apeared, so I tested the demo with both connected, and now I can see everything in the screen. 

P.S. The screen is a ssd1327 (I2C only), named at the back with GME128128-02.

Thank you very much for your library.

**Comment by lexus2k** [comment]
Hi, You have slightly confused me. ;)  What was the root cause for the issue? Pull up resistors?

**Comment by Alvatros96** [comment]
I honestly don't know yet, maybe a poor quality screen from aliexpress.
