### ISSUE TITLE
How to connect OLED ssd1306 128 x 64 to ESP 32 cam

### ISSUE THREAD

**Issue by lancer-1** [lexus2k/lcdgfx#55]
pins:
SDA - 14
SCL - 15
RST - NONE

can't do it by default constructor...

help pls

**Comment by lexus2k** [comment]
Hi,

What about anything like this:

```.cpp
DisplaySSD1306_128x64_I2C display(-1, {I2C_NUM_1, -1, 15, 14, 0});
```
where -1 = RESET PIN, I2C_NUM_1 = number of spi bus on ESP32, -1 is to use default i2c address for the display, 15 = SCL, 14 = SDA, 0 = frequency 400kHz by default.

https://codedocs.xyz/lexus2k/lcdgfx/class_display_s_s_d1306__128x64___i2_c.html#a3f7a6b8f70aff8e2a8c4b4c2b2c9f03d

**Comment by lancer-1** [comment]
thanks a lot!
