### ISSUE TITLE
drawLinesDemo() get a broken line 

### ISSUE THREAD

**Issue by Chihhao** [lexus2k/lcdgfx#58]
in ssd1306_demo, i run the sub method drawLinesDemo() and got a broken image. i don't know how to fix, pls help, thx.

<img width="820" alt="pic" src="https://user-images.githubusercontent.com/10015954/118392374-0023c700-b66c-11eb-820f-b9e438a64480.png">

**Comment by lexus2k** [comment]
Hi,

That's expected behavior for direct API without double buffering. Please, refer to #24, and the same issue for C-style library: https://github.com/lexus2k/ssd1306/issues/70

**Comment by Chihhao** [comment]
Now I get it! Thx!
