### ISSUE TITLE
Cannot build using this library for esp32

### ISSUE THREAD

**Issue by blmhemu** [lexus2k/lcdgfx#60]
**Describe the bug**
Cannot build using the library.

**To Reproduce**
1. Go to esp-arduino-blink example in platformio
2. Add this library as dependency
3. use `#include "lcdgfx.h"` in the main.cpp
4. Build the project.

**Expected behavior**
Program should build

**Screenshots**
![image](https://user-images.githubusercontent.com/19410501/119254786-fd7a2200-bbd5-11eb-8c28-9d9eb8a3dd0f.png)
Looks like the attach interrupt in being exported by two libraries (esp-arduino and this lib) ?

**Please complete the following information:**
 - 1.1
 - SSD1306
 - MacOS
 - ESP32
 - VSCODE - PlatformIO

**Additional context**
None

**Comment by lexus2k** [comment]
Hi,

Can you try to add -DARDUINO to your project defines?

**Comment by blmhemu** [comment]
Thanks for the quick response!

![image](https://user-images.githubusercontent.com/19410501/119337593-a5621f00-bcac-11eb-9280-e13b3f4fcb46.png)
After I added `-D ARDUINO` I got the above error

Actually I am using arduino AND esp-idf (Both of them as the project is dependent on some arduino libs)

**Comment by lexus2k** [comment]
Please, find the fix on the master branch (latest commit), ARDUINO define is not required.

**Comment by blmhemu** [comment]
Greetings ! @lexus2k 
That was a nice fix. The problem can be marked as resolved In master. Eager to see it in new release !

Once again thanks for the quick fix !
