### ISSUE TITLE
How to use multiple displays?

### ISSUE THREAD

**Issue by mcbainu** [lexus2k/lcdgfx#61]
Hi there,

someone has a working example to use for two or even more displays? Regardless if two of the same type or different ones. How to deal with the correct CS selecting the right display? Maybe someone ever did this and can help a little bit with this.

Thanks and best regards

**Comment by lexus2k** [comment]
Hi, how about the case below? You need to specify only CS pin different.

```.cpp
DisplaySSD1331_96x64x8_SPI display1(4,{-1, 6, 5, 0,-1,-1}); // 4 - RST, 6 - CS, 5 - DC 
DisplaySSD1331_96x64x8_SPI display2(4,{-1, 9, 5, 0,-1,-1}); // 4 - RST, 9 - CS, 5 - DC 
```
