### ISSUE TITLE
ESP32 C3

### ISSUE THREAD

**Issue by elgerg** [lexus2k/lcdgfx#68]
Hi,

Does (or will) this library support the ESP32 C3 or S2?

Thanks!

**Comment by elgerg** [comment]
Hi,

So I gave that a go and ended up no further.

Can you tell me what address it's trying to write to? My display is currently set to 0x78 but can be changed to 0x7a.

Thanks
Alex

**Comment by elgerg** [comment]
Might be related to it being a 1327 not a 1306?

**Comment by elgerg** [comment]
Its an I2C display not SPI so probably that still being a problem. Any ideas?

**Comment by elgerg** [comment]
Ok, i tried and now get:

/home/alex/Arduino/ssd1306_demo/ssd1306_demo/ssd1306_demo.ino: In function 'void setup()':
ssd1306_demo:168:69: error: too many arguments to function 'void ssd1306_128x64_i2c_init()'
     ssd1306_128x64_i2c_init(-1, {-1, 0, SCL_PIN_NUM, SDA_PIN_NUM, 0});
                                                                     ^
In file included from /home/alex/Arduino/libraries/ssd1306/src/ssd1306.h:39,
                 from /home/alex/Arduino/ssd1306_demo/ssd1306_demo/ssd1306_demo.ino:39:
/home/alex/Arduino/libraries/ssd1306/src/lcd/oled_ssd1306.h:61:14: note: declared here
 void         ssd1306_128x64_i2c_init(void);
              ^~~~~~~~~~~~~~~~~~~~~~~
exit status 1
too many arguments to function 'void ssd1306_128x64_i2c_init()'

Any ideas?

**Comment by elgerg** [comment]
If i try with:
    ssd1306_128x64_i2c_init();

I get:
/home/alex/Arduino/libraries/ssd1306/src/intf/vga/esp32/vga128x64.cpp:51:8: error: 'CompositeOutput' does not name a type
 static CompositeOutput output(CompositeOutput::PAL);
        ^~~~~~~~~~~~~~~
/home/alex/Arduino/libraries/ssd1306/src/intf/vga/esp32/vga128x64.cpp: In function 'void compositeCore(void*)':
/home/alex/Arduino/libraries/ssd1306/src/intf/vga/esp32/vga128x64.cpp:58:9: error: 'output' was not declared in this scope
         output.sendFrameHalfResolution(__vga_buffer);
         ^~~~~~
/home/alex/Arduino/libraries/ssd1306/src/intf/vga/esp32/vga128x64.cpp: In function 'void vga_controller_send_byte(uint8_t)':
/home/alex/Arduino/libraries/ssd1306/src/intf/vga/esp32/vga128x64.cpp:158:9: error: 'output' was not declared in this scope
         output.init(s_width, s_height, s_bpp);
         ^~~~~~
exit status 1
Error compiling for board ESP32C3 Dev Module.


Feel like I'm banging my head against a brick wall..

**Comment by elgerg** [comment]
Ok, it might be that the documentation that specifies what IO > ardiono pin numbers doesnt exist or i'm just doing something wrong. I just cant seem to get it to work.

I did think that the pins were right as IO3 and IO4 are the red and green RGB led pins but i still cant seem to get it to work.

Could the addresses (0x78 and 0x7a) be wrong?

Any help would really be appreciated.

If it would help I can arrange for a dev board to be shipped out to you?

**Comment by lexus2k** [comment]
> Can you tell me what address it's trying to write to? My display is currently set to 0x78 but can be changed to 0x7a.

You need to pass i2c address to SPlatformI2cConfig structure: https://codedocs.xyz/lexus2k/lcdgfx/struct_s_platform_i2c_config.html

I believe it should be either 0x3C (0x78 / 2) or 0x3D  (0x7a / 2). But you need to check against the datasheet.

> I did think that the pins were right as IO3 and IO4 are the red and green RGB led pins but i still cant seem to get it to work.

So, do you say that D3, D4 don't work for you ?

> If it would help I can arrange for a dev board to be shipped out to you?

Of course, you can, but it will take around 1 month for the board to get here.

**Comment by ITstreet1** [comment]
For ESP32-C3, I2C should be IO8 and IO9.

**Comment by elgerg** [comment]
Testing with another screen/board.

Will let you know the outcome as soon as I can..
