### ISSUE TITLE
How to write int variable

### ISSUE THREAD

**Issue by Ignmarsti** [lexus2k/lcdgfx#75]
Hello. I am trying to print on an Oled SSD1306 processed data that I receive from a MAX30102 sensor, specifically, the data is heart rate and oxygen saturation. However, I am not able to print them on the OLED. I have tried to display them as * char and as a string, but the results have not been what I expected. I wanted to know if there is any way to display them as integers.
Thanks in advance.

**Comment by lexus2k** [comment]
Use `display.print(10)` or `display.print(2.2f)`.
If that doesn't work for, let me know.
