### ISSUE TITLE
 'SPI_DMA_DISABLED' was not declared

### ISSUE THREAD

**Issue by KaiJiao** [lexus2k/lcdgfx#81]
**Describe the bug**
C:\Users\jiao\Documents\Arduino\libraries\lcdgfx\src\lcd_hal\esp\esp32_spi.cpp: In member function 'void EspSpi::begin()':
C:\Users\jiao\Documents\Arduino\libraries\lcdgfx\src\lcd_hal\esp\esp32_spi.cpp:90:66: error: 'SPI_DMA_DISABLED' was not declared in this scope:
spi_bus_initialize(m_busId ? VSPI_HOST : HSPI_HOST, &buscfg, SPI_DMA_DISABLED); // 0 -no dma

When I verify an empty code which just include the lcdgfx library in Arduino IDE, it shows this error. 

Do you know how can I modify it? Thank you very much!

Kai

<img width="1107" alt="微信截图_20220211050236" src="https://user-images.githubusercontent.com/94878871/153540200-4314e83e-5c4b-4f80-b404-f531c0d6c57b.png">

**Comment by lexus2k** [comment]
Hi, just replace SPI_DMA_DISABLED with 0.

This is inconsistency in different SDK versions.

**Comment by lexus2k** [comment]
Le me know if it works for you.

Also it would be nice to get know the version of the tools and the board you're using.

**Comment by KaiJiao** [comment]
Sorry for my late reply, yes that's work for me! Thank you very much!

**Comment by lexus2k** [comment]
To prevent such issue in the future, I have updated the code to use 0 on the latest master branch.

**Comment by CNSNGopenSourceProjects** [comment]
It should be nice if to publish this library fix for Arduino IDE.
The bug fix work for me.
Thank you.

**Comment by lexus2k** [comment]
Done. v1.1.4 will be available soon from Arduino IDE.
