### ISSUE TITLE
[RPi 4][IC2] `Failed to write to the i2c bus: Bad file descriptor.`

### ISSUE THREAD

**Issue by Bricklou** [lexus2k/lcdgfx#84]
**Describe the bug**
I'm trying to use the library on my Raspberry Pi, but for some reason I get the following error:
```
Failed to write to the i2c bus: Bad file descriptor.
```

**To Reproduce**
1. Create following files
```cpp
// src/main.cpp
#include <iostream>
#include <lcdgfx.h>
#include <lcdgfx_gui.h>
#include <cstdint>

int main() {
        DisplaySSD1306_128x64_I2C display(-1);

        display.clear();
}
```

```cmake
// CMakeLists.txt
cmake_minimum_required(VERSION 3.17)

project(screen_monitor
        VERSION 1.0.0
        LANGUAGES C CXX
)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20 -Wall -Wextra -fPIC -rdynamic -pthread")

# ==========
# lcdgfx
# ==========
add_subdirectory(libs/lcdgfx)

# ==========
# screen_monitor
# ==========
add_executable(${PROJECT_NAME}
        src/main.cpp
)

target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_20)
set_target_properties(${PROJECT_NAME} PROPERTIES
        CXX_STANDARD 20
        CXX_STANDARD_REQUIRED ON
)

target_link_libraries(${PROJECT_NAME} PUBLIC lcdgfx)
target_include_directories(${PROJECT_NAME} PUBLIC
        libs/lcdgfx/src
)

if (CMAKE_BUILD_TYPE MATCHES "^[Rr]elease")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s -02 -0s")
else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
endif()
```
2. Clone the lib into `libs/lcdgfx`
3. Build the app
5. See error

**Expected behavior**
The program should run, but throws the error instead.

**Please complete the following information:**
 - library version: [14b55ab](https://github.com/lexus2k/lcdgfx/commit/14b55ab6b72709ef7142c690d784cb9b683da1b3) and master
 - LCD display type: SSD1306
 - OS: raspberry OS - debian 11
 - Platform: Raspberry Pi 4

**Additional context**
I tried to run the demo program using this link: https://github.com/lexus2k/lcdgfx/wiki/FAQ#how-to-run-demos-on-raspberry-pi
and it worked perfectly fine, but not with my own code. :confused:

**Comment by lexus2k** [comment]
Hi,

What about `display.begin()` in your code?
Please check your code carefully.

**Comment by Bricklou** [comment]
Oh, yes ! Looks like it was missing.
Thank you :sweat_smile:
